### ISSUE TITLE
Adding Alternative Emails page issue

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/docs#11]
@sharangowd The first line states that "You can also add the alternative emails to your LF account. You can use these alternative emails to login to your LF account."

This is incorrect - you cannot log into your account with an alternative email. You can only use your primary email or username.

**Comment by sharangowd** [comment]
@WillsonHG Hi Willson, Thanks for providing your comment. 

My Profile page was developed recently. I will check with the concerned engineer to know the use case scenarios for Alternative Emails in My Profile. Based on their inputs, will update the document accordingly.

**Comment by sharangowd** [comment]
I don't see this sentence now in the documentation.

**Comment by sharangowd** [comment]
Cant see the mentioned sentence in the documentation
