### ISSUE TITLE
Broken link on 'Get reimbursed' page

### ISSUE THREAD

**Issue by hs2361** [communitybridge/docs#64]
The link to the page with instructions on how to submit Expensify reports is broken. The [current link](https://docs.linuxfoundation.org/docs/communitybridge/crowd-funding/how-to-create-and-submit-an-expensify-report) given here https://github.com/communitybridge/docs/blob/master/crowdfunding/get-reimbursed.md#L54
is broken, and leads to a page that does not exist.

This should be replaced with the link to the new page - https://docs.linuxfoundation.org/lfx/crowdfunding/how-to-create-and-submit-an-expensify-report

**Comment by sharangowd** [comment]
Thanks Harsh for catching this, we have updated the document with the correct link.
